from panda3d import core


class Room:
    def __init__(self):
        self.root = core.NodePath('Room')
        self.root.clear_light()
        #dlight = core.DirectionalLight('dlight')
        #dlight.set_color_temperature(6500)
        #dlnp = self.root.attach_new_node(dlight)
        #dlnp.set_light(dlnp)
        self.buff = base.win.make_texture_buffer('Room Buffer', 2048, 2048)

        self.mytex = self.buff.get_texture()
        self.mytex.set_wrap_u(core.Texture.WM_clamp)
        self.mytex.set_wrap_v(core.Texture.WM_clamp)
        self.buff.set_sort(-100)
        self.cam = base.make_camera(self.buff)
        self.cam.reparent_to(self.root)
        self.cam.set_r(180)
        #self.sm = base.loader.load_model('box')
        #self.sm.reparent_to(self.root)
        #self.sm.set_pos(10, 5, 0)
        #self.sm2 = base.loader.load_model('smiley.egg')
        #self.sm2.reparent_to(self.root)
        #self.sm2.set_pos(0, -8, 1)
        #self.sm2.clear_texture()
        #self.sm2.find('**').clear_texture()
        #self.sm2.set_color(core.Vec4(1, 0, 0, 1))
        #self.cam.set_pos(0, -12, 2)
        #self.cam.look_at(self.sm)
        #self.door = self.root.attach_new_node('Door')
        #self.door.set_pos(0, -10, 1)
        rooms = loader.load_model('assets/rooms.blend')
        self.room = rooms.find('**/room_d')
        self.room.reparent_to(self.root)
        self.room.clear_light()
        self.room.set_pos(0, 0, 0)
        self.door = self.room.find('**/door*')
        self.door.hide()
        self.door_focus = self.door.attach_new_node('door focus')
        self.door_focus.set_pos(0, 0, 1.5)
        self.cam.node().show_frustum()
        #smil = loader.load_model('smiley.egg')
        #smil.reparent_to(self.room)
        #smil.set_pos(0, 0, 1)
        #smil.set_scale(0.5)
